services:
  alicdn-update:
    image: alicdn-update:1.1.0
    container_name: alicdn-update
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/wuhunyu/applications/cert:/app/sslPath:ro
      - /home/wuhunyu/applications/alicdn-update/logs:/var/logs
    environment:
      - TZ=Asia/Shanghai
      - accessKeyId=
      - accessKeySecret=
      - domains=static.wuhunyu.top:api.wuhunyu.top
      - sslPath=/app/sslPath
      - pubes=static.wuhunyu.top.cer:api.wuhunyu.top.cer
      - pries=static.wuhunyu.top.key:api.wuhunyu.top.key
      - scheduledCron=0 0 1 * * ?
      - JAVA_OPTS=-Xms256m -Xmx256m